### ISSUE TITLE
Move rapp launching info from android app to app manager for direct connections

### ISSUE THREAD

**Issue by bit-pirate** [rosjava/android_apps#23]
For direct connections the app manager currently uses the default app hardcoded into the android app (e.g. https://github.com/ros-java/android_apps/blob/hydro-devel/teleop/src/main/res/values/strings.xml).

This information is not used when using the robot remocon. If at some points it turns out that direct connections are essential, we should find a way to configure default rapps for android apps in the app manager.

**Comment by stonier** [comment]
Some other tidbits from the conversation:

Having all pairing mode information (for direct and for robot remocon connections) in the rapp manager is more convenient than having it in both remocon and android app. I can't think of any real negatives for doing this.

Having said that, as marcus said, we currently only use direct connections for development and debugging. That makes this string information in the android app easy to hack if you want to. We don't have a good reason for supporting this officially yet, since all our use cases officially go via the remocon. If this situation changes....

**Comment by stonier** [comment]
The interactions manager update moves all of this to the pc. No problem anymore.
